import type { EnemyKind } from "./types";

export interface EnemySpec {
  label: string;
  health: number;
  speed: number;
  scale: number;
  radius: number;
  zigzag: number;
  stopZ: number;
  fireEvery: number;
  supportEvery: number;
  flying: boolean;
  armor: number;
  frontShield: boolean;
  splits: EnemyKind | null;
  splitCount: number;
  leakCost: number;
  bounty: number;
  score: number;
  boss: boolean;
  skin: string;
}

export const ENEMY_SPECS: Record<EnemyKind, EnemySpec> = {
  militia: {
    label: "Milis",
    health: 0.6,
    speed: 3.6,
    scale: 0.9,
    radius: 0.42,
    zigzag: 0,
    stopZ: 99,
    fireEvery: 0,
    supportEvery: 0,
    flying: false,
    armor: 0,
    frontShield: false,
    splits: null,
    splitCount: 0,
    leakCost: 1,
    bounty: 3,
    score: 10,
    boss: false,
    skin: "militia",
  },
  infantry: {
    label: "Piyade",
    health: 1,
    speed: 2.3,
    scale: 1,
    radius: 0.46,
    zigzag: 0.9,
    stopZ: 99,
    fireEvery: 0,
    supportEvery: 0,
    flying: false,
    armor: 0,
    frontShield: false,
    splits: null,
    splitCount: 0,
    leakCost: 1,
    bounty: 4,
    score: 12,
    boss: false,
    skin: "infantry",
  },
  heavy: {
    label: "Ağır Zırhlı",
    health: 4,
    speed: 1.35,
    scale: 1.4,
    radius: 0.66,
    zigzag: 0,
    stopZ: 99,
    fireEvery: 0,
    supportEvery: 0,
    flying: false,
    armor: 0.2,
    frontShield: false,
    splits: null,
    splitCount: 0,
    leakCost: 2,
    bounty: 9,
    score: 26,
    boss: false,
    skin: "heavy",
  },
  marksman: {
    label: "Nişancı",
    health: 0.8,
    speed: 1.9,
    scale: 1,
    radius: 0.46,
    zigzag: 0,
    stopZ: -12,
    fireEvery: 1.7,
    supportEvery: 0,
    flying: false,
    armor: 0,
    frontShield: false,
    splits: null,
    splitCount: 0,
    leakCost: 1,
    bounty: 6,
    score: 18,
    boss: false,
    skin: "marksman",
  },
  sapper: {
    label: "İntihar Bombacısı",
    health: 1.6,
    speed: 2.6,
    scale: 1.15,
    radius: 0.54,
    zigzag: 0.5,
    stopZ: 99,
    fireEvery: 0,
    supportEvery: 0,
    flying: false,
    armor: 0,
    frontShield: false,
    splits: "militia",
    splitCount: 2,
    leakCost: 2,
    bounty: 7,
    score: 20,
    boss: false,
    skin: "sapper",
  },
  drone: {
    label: "Drone",
    health: 0.9,
    speed: 3.2,
    scale: 0.7,
    radius: 0.4,
    zigzag: 1.6,
    stopZ: 99,
    fireEvery: 0,
    supportEvery: 0,
    flying: true,
    armor: 0,
    frontShield: false,
    splits: null,
    splitCount: 0,
    leakCost: 1,
    bounty: 8,
    score: 24,
    boss: false,
    skin: "drone",
  },
  apc: {
    label: "Zırhlı Araç",
    health: 7,
    speed: 1.1,
    scale: 1.7,
    radius: 0.85,
    zigzag: 0,
    stopZ: -8,
    fireEvery: 1.2,
    supportEvery: 0,
    flying: false,
    armor: 0.45,
    frontShield: false,
    splits: "infantry",
    splitCount: 3,
    leakCost: 3,
    bounty: 22,
    score: 70,
    boss: false,
    skin: "apc",
  },
  mortar: {
    label: "Havan Ekibi",
    health: 1.4,
    speed: 1.2,
    scale: 1.05,
    radius: 0.5,
    zigzag: 0,
    stopZ: -16,
    fireEvery: 0,
    supportEvery: 3.4,
    flying: false,
    armor: 0.1,
    frontShield: false,
    splits: null,
    splitCount: 0,
    leakCost: 1,
    bounty: 12,
    score: 34,
    boss: false,
    skin: "mortar",
  },
  medic: {
    label: "Sıhhiyeci",
    health: 1.2,
    speed: 2,
    scale: 1,
    radius: 0.46,
    zigzag: 0.4,
    stopZ: 99,
    fireEvery: 0,
    supportEvery: 2.2,
    flying: false,
    armor: 0,
    frontShield: false,
    splits: null,
    splitCount: 0,
    leakCost: 1,
    bounty: 11,
    score: 30,
    boss: false,
    skin: "medic",
  },
  shield: {
    label: "Kalkanlı",
    health: 2.6,
    speed: 1.6,
    scale: 1.25,
    radius: 0.62,
    zigzag: 0,
    stopZ: 99,
    fireEvery: 0,
    supportEvery: 0,
    flying: false,
    armor: 0.15,
    frontShield: true,
    splits: null,
    splitCount: 0,
    leakCost: 2,
    bounty: 13,
    score: 36,
    boss: false,
    skin: "shield",
  },
  jammer: {
    label: "Parazit",
    health: 1.8,
    speed: 2.1,
    scale: 1.05,
    radius: 0.5,
    zigzag: 0.7,
    stopZ: 99,
    fireEvery: 0,
    supportEvery: 5,
    flying: false,
    armor: 0.1,
    frontShield: false,
    splits: null,
    splitCount: 0,
    leakCost: 1,
    bounty: 15,
    score: 42,
    boss: false,
    skin: "jammer",
  },
  commander: {
    label: "Komutan",
    health: 42,
    speed: 1,
    scale: 2.2,
    radius: 1.15,
    zigzag: 0,
    stopZ: -9,
    fireEvery: 1.4,
    supportEvery: 9,
    flying: false,
    armor: 0.25,
    frontShield: false,
    splits: "heavy",
    splitCount: 2,
    leakCost: 4,
    bounty: 90,
    score: 500,
    boss: true,
    skin: "commander",
  },
};

export const ENEMY_KINDS = Object.keys(ENEMY_SPECS) as readonly EnemyKind[];

const UNLOCK_WAVE: Record<EnemyKind, number> = {
  militia: 1,
  infantry: 1,
  heavy: 3,
  marksman: 4,
  sapper: 6,
  drone: 8,
  apc: 12,
  mortar: 15,
  medic: 18,
  shield: 20,
  jammer: 24,
  commander: 5,
};

export function kindsForWave(wave: number): EnemyKind[] {
  return ENEMY_KINDS.filter((kind) => !ENEMY_SPECS[kind].boss && UNLOCK_WAVE[kind] <= wave);
}

export function unlockWaveOf(kind: EnemyKind): number {
  return UNLOCK_WAVE[kind];
}
