import type { GunlineAttachment, GunlineWeapon, WeaponId } from "./types";

export const WEAPONS: Record<WeaponId, GunlineWeapon> = {
  pistol: {
    id: "pistol",
    label: "Tabanca",
    detail: "Sicil silahı. Her erin belinde var.",
    tier: 0,
    damage: 10,
    interval: 0.3,
    pellets: 1,
    spread: 0,
    speed: 18,
    pierce: 0,
    aoe: 0,
    antiAir: false,
    cost: 0,
  },
  smg: {
    id: "smg",
    label: "Hafif Makineli",
    detail: "Yakın mesafede yağmur gibi.",
    tier: 1,
    damage: 8,
    interval: 0.14,
    pellets: 1,
    spread: 0.05,
    speed: 20,
    pierce: 0,
    aoe: 0,
    antiAir: false,
    cost: 400,
  },
  shotgun: {
    id: "shotgun",
    label: "Pompalı",
    detail: "Beş saçma, geniş koni.",
    tier: 1,
    damage: 9,
    interval: 0.5,
    pellets: 5,
    spread: 0.22,
    speed: 17,
    pierce: 0,
    aoe: 0,
    antiAir: false,
    cost: 550,
  },
  rifle: {
    id: "rifle",
    label: "Piyade Tüfeği",
    detail: "Dengeli. Cephede standart.",
    tier: 2,
    damage: 26,
    interval: 0.34,
    pellets: 1,
    spread: 0.02,
    speed: 24,
    pierce: 0,
    aoe: 0,
    antiAir: true,
    cost: 900,
  },
  lmg: {
    id: "lmg",
    label: "Ağır Makineli",
    detail: "Bandı bitene kadar susmaz.",
    tier: 3,
    damage: 14,
    interval: 0.1,
    pellets: 1,
    spread: 0.07,
    speed: 26,
    pierce: 1,
    aoe: 0,
    antiAir: true,
    cost: 1600,
  },
  dmr: {
    id: "dmr",
    label: "Keskin Nişancı",
    detail: "Tek atış, zırhı deler.",
    tier: 3,
    damage: 78,
    interval: 0.62,
    pellets: 1,
    spread: 0,
    speed: 40,
    pierce: 2,
    aoe: 0,
    antiAir: true,
    cost: 1900,
  },
  launcher: {
    id: "launcher",
    label: "Bombaatar",
    detail: "Yavaş, ama kalabalığı dağıtır.",
    tier: 4,
    damage: 46,
    interval: 0.8,
    pellets: 1,
    spread: 0.03,
    speed: 16,
    pierce: 0,
    aoe: 2.1,
    antiAir: false,
    cost: 2600,
  },
  rail: {
    id: "rail",
    label: "Raylı Top",
    detail: "Hattı baştan sona deler.",
    tier: 5,
    damage: 120,
    interval: 0.9,
    pellets: 1,
    spread: 0,
    speed: 60,
    pierce: 6,
    aoe: 0.9,
    antiAir: true,
    cost: 4200,
  },
};

export const WEAPON_ORDER: readonly WeaponId[] = [
  "pistol",
  "smg",
  "shotgun",
  "rifle",
  "lmg",
  "dmr",
  "launcher",
  "rail",
];

export const ATTACHMENTS: readonly GunlineAttachment[] = [
  {
    id: "barrel-compensator",
    slot: "barrel",
    label: "Namlu Freni",
    detail: "Saçılma azalır, isabet artar.",
    cost: 300,
    damage: 1,
    fireRate: 1,
    pellets: 0,
    pierce: 0,
    crit: 0,
    spread: 0.55,
  },
  {
    id: "barrel-heavy",
    slot: "barrel",
    label: "Ağır Namlu",
    detail: "Hasar +%18, atış hızı -%8.",
    cost: 520,
    damage: 1.18,
    fireRate: 0.92,
    pellets: 0,
    pierce: 0,
    crit: 0,
    spread: 1,
  },
  {
    id: "barrel-piercer",
    slot: "barrel",
    label: "Delici Uç",
    detail: "Mermi bir düşman daha deler.",
    cost: 700,
    damage: 1,
    fireRate: 1,
    pellets: 0,
    pierce: 1,
    crit: 0,
    spread: 1,
  },
  {
    id: "mag-extended",
    slot: "mag",
    label: "Uzun Şarjör",
    detail: "Atış hızı +%15.",
    cost: 340,
    damage: 1,
    fireRate: 1.15,
    pellets: 0,
    pierce: 0,
    crit: 0,
    spread: 1,
  },
  {
    id: "mag-buckshot",
    slot: "mag",
    label: "Saçma Şarjör",
    detail: "+1 mermi, saçılma artar.",
    cost: 620,
    damage: 0.92,
    fireRate: 1,
    pellets: 1,
    pierce: 0,
    crit: 0,
    spread: 1.35,
  },
  {
    id: "mag-match",
    slot: "mag",
    label: "Seçme Fişek",
    detail: "Hasar +%12.",
    cost: 560,
    damage: 1.12,
    fireRate: 1,
    pellets: 0,
    pierce: 0,
    crit: 0,
    spread: 0.9,
  },
  {
    id: "optic-reflex",
    slot: "optic",
    label: "Kolimatör",
    detail: "Kritik +%8.",
    cost: 380,
    damage: 1,
    fireRate: 1,
    pellets: 0,
    pierce: 0,
    crit: 0.08,
    spread: 0.85,
  },
  {
    id: "optic-thermal",
    slot: "optic",
    label: "Termal Dürbün",
    detail: "Kritik +%15, gece körlüğü yok.",
    cost: 880,
    damage: 1,
    fireRate: 1,
    pellets: 0,
    pierce: 0,
    crit: 0.15,
    spread: 0.6,
  },
  {
    id: "optic-laser",
    slot: "optic",
    label: "Lazer İşaretleyici",
    detail: "Saçılma yarıya iner.",
    cost: 460,
    damage: 1.04,
    fireRate: 1,
    pellets: 0,
    pierce: 0,
    crit: 0,
    spread: 0.5,
  },
];

export function attachmentById(id: string): GunlineAttachment | null {
  return ATTACHMENTS.find((item) => item.id === id) ?? null;
}

export function attachmentsForSlot(slot: GunlineAttachment["slot"]): GunlineAttachment[] {
  return ATTACHMENTS.filter((item) => item.slot === slot);
}

export function weaponUnlockTier(weapon: WeaponId): number {
  return WEAPONS[weapon].tier;
}

export function nextWeapon(weapon: WeaponId): WeaponId | null {
  const index = WEAPON_ORDER.indexOf(weapon);
  return WEAPON_ORDER[index + 1] ?? null;
}
